
name: extension-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    env:
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - id: packExtensionDir
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: 'build/chrome'
          zipFilePath: 'image-steam.zip'
      - name: build chromr extension
        uses: cardinalby/webext-buildtools-chrome-crx-action@v2
        with:
          zipFilePath: 'image-steam.zip'
          crxFilePath: 'image-steam.crx'
          privateKey: ${{ secrets.CHROME_CRX_PRIVATE_KEY }} 
      - name: build firefox extension
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: build/firefox
          filename: "image-steam-{version}.xpi"
      - name: "Upload Artifact"
        uses: actions/upload-artifact@master
        with:
          name: image-steam-{version}.xpi image-steam.crx
          path: ${{ steps.web-ext-build.outputs.target }}

    